# pull the official base image
FROM node:alpine
# set working direction
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
# install application dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install
# add app
COPY . ./
# start app
CMD ["npm", "run", "start"]