# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integrate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Latest Repo
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'

    - name: Run tests
      uses: npm test


  deploy:

    needs: integrate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest Repo
      uses: actions/checkout@v2
    
    - name: Generate Deployment Package
      run: zip -r deploy.zip * -x "**node_modules**"
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Letterwell Frontend
        environment_name: Letterwellfrontend-env
        version_label: ${{github.SHA}}
        region: eu-west-2
        deployment_package: deploy.zip





